### ISSUE TITLE
Github直接阅读的体验改善

### ISSUE THREAD

**Issue by suqi** [eastlakeside/interpy-zh#15]
一些v2ex网友(@nightv2 )反馈，github直接阅读时，想增加回到目录的链接。

这个需要参考下别的github书籍来改进一下， 一个可改进的就是，

我们的一些小节非常短，可以合并成一个大节，这样就可以减少翻页和回到目录的需求

甚至，可以合成一个超大单页书

**Comment by liuyu** [comment]
原著的想法就是一个小节，一个点，的确不太方便快速阅读。

可以考虑做一些合并的操作。

**Comment by leeoo** [comment]
赞成合并一些节点，但是不建议合成一个超大单页书，否则做成mobi/epub后可能会让Kindle/Kobo等电子书“炸掉”...

**Comment by suqi** [comment]
会在这个issue中统一优化： #49
