### ISSUE TITLE
群已经超过100人了，不能再扫码进入了，已经进群的小伙伴方不方便拉我进去？

### ISSUE THREAD

**Issue by Panmax** [eastlakeside/interpy-zh#17]
下边是我的二维码，谢谢各位啦！

![wechat_1459478823](https://cloud.githubusercontent.com/assets/3353761/14196452/163becb8-f7f7-11e5-8705-e783032ac2dc.jpeg)

**Comment by liuyu** [comment]
已加你，正在想办法升级群。
