### ISSUE TITLE
微信群已满100人，需要邀请才能入群。规则如下：

### ISSUE THREAD

**Issue by liuyu** [eastlakeside/interpy-zh#19]
微信群已满100人，需要邀请才能入群。规则如下：
1. 扫描以下2维码
2. 备注：姓名-公司-职位/职业

> 群规：
> 仅限讨论技术，聊聊新的想法，翻译事等。禁止灌水，发与技术无关的图片。

![image](https://cloud.githubusercontent.com/assets/104815/14198021/36e97d20-f808-11e5-8c4e-c5335e7b0a74.png)

**Comment by Iwrbw** [comment]
二维码找不到用户了

**Comment by muxueqz** [comment]
![default](https://user-images.githubusercontent.com/730639/44641213-75e92f80-a9f8-11e8-854f-ce06b38a84f0.png)
@Iwrbw 你可以加我，然后我邀请你进群

**Comment by Sophie521** [comment]
求拉进群学习交流，我微信1251799785，谢谢。
