### ISSUE TITLE
Generators章节的建议

### ISSUE THREAD

**Issue by fengbeihong** [eastlakeside/interpy-zh#21]
在定义Iterable或Iterator的含义时，直接按照英文的顺序翻译过来效果并不好，中文会让人理解错误。

原文：
一个迭代器是任意一个对象，只要它定义了一个next(Python2) 或者__next__方法。
建议：
任意一个对象，只要定义了next(Python2) 或者__next__方法，它就是迭代器。

**Comment by suqi** [comment]
这个翻译不错，信雅达，来吧，欢迎PullRequest~
