### ISSUE TITLE
 关于map的返回类型

### ISSUE THREAD

**Issue by oudb** [eastlakeside/interpy-zh#23]
在4.1Map小节里的"squared = list(map(lambda x: x**2, items))"里的“list”是否多余？因为map返回类型就是list。
<img width="338" alt="e3d7abe2-6a3d-4921-9d19-6e3c20200477" src="https://cloud.githubusercontent.com/assets/6326847/14204347/559d4fca-f836-11e5-889e-da26b7df1f49.png">

**Comment by xutaoding** [comment]
你应该在python2.7.x的版本下编码到， map函数在python3.x下返回到是一个迭代器， 那么用list(map(...)), 适用于两个版本

**Comment by suqi** [comment]
@xutaoding 说的有道理， 这个list确实是专门为了兼容python3

这里如果要改进下代码的话，感觉是不是应该把list放到print中去，因为在print时才需要转换成一个列表来显示。
