### ISSUE TITLE
代码问题：基于类的装饰器

### ISSUE THREAD

**Issue by suqi** [eastlakeside/interpy-zh#25]
@jinxingxing   比如基于类的装饰器

其他代码要再review一下

PS: 目前代码方面都没有动过原著的，一些代码问题需要给原著提issue

**Comment by jinxingxing** [comment]
找到原著的一个PR: https://github.com/yasoob/intermediatePython/pull/92
直接运行示例代码（没有调用 myfunc1）的效果也像是装饰器工作了，所以就没人注意 review 吧

**Comment by suqi** [comment]
感谢 @jinxingxing  看来我们国内的读者比原著还是认真严谨一些 :+1:  :100:
