### ISSUE TITLE
2.7版本的python代码

### ISSUE THREAD

**Issue by legendtkl** [eastlakeside/interpy-zh#28]
打算做一个所有代码的2.7版本，有需要吗？

**Comment by suqi** [comment]
感谢建议！

目前的示例代码都做到了2和3的兼容性，因此也损失了一定的简洁性，请问你也是出于这方面考虑要做么

感觉目前大部分代码，其实跟用2.7实现的代码差别不大吧

你能举个例子，然后看看怎么展示给读者看呢

**Comment by legendtkl** [comment]
是的啊，我昨天下午都实现了一遍，确实差别不大。除了map, filter前的list是多余的。

**Comment by legendtkl** [comment]
或者作为书的配套代码怎么样

**Comment by suqi** [comment]
@legendtkl  感谢热心，那太好了，你都实现了一遍，那就快来个PR吧~

把代码放到code/2.7/ 目录里，然后在Readme.md上加一个代码参考的说明，如何

**Comment by legendtkl** [comment]
done， PR #31

**Comment by suqi** [comment]
感谢，已merge，
我会在Readme里添加代码运行的说明
