### ISSUE TITLE
部分延伸内容扩充的问题

### ISSUE THREAD

**Issue by suqi** [eastlakeside/interpy-zh#29]
由v2ex网友glumes提出：

python 新手，想用 python 做一些更炫的事情的话，大多要导入其他模块吧。 
所以，楼主能给些建议如何去知道了解有第三方模块，以及学习掌握他们呢？

**Comment by suqi** [comment]
先简短回复，可以先去看看http://awesome-python.com/， http://www.fullstackpython.com/， 里面列举了去做更炫的事情的各方面的开源库。

其他的内容我们后续扩充下看看如何加到书里去

**Comment by liuyu** [comment]
可以结合 #15 的问题，将书进行结构的简化调整，然后增加一个章节，切一个新的分支，来增加这些内容。大家一起维护。
