### ISSUE TITLE
pdf版本显示不完整

### ISSUE THREAD

**Issue by klzsysy** [eastlakeside/interpy-zh#48]
文中的部分长名函数显示不全，没法换行，缩放不起作用，如图为第一个装饰器那一章

![image](https://cloud.githubusercontent.com/assets/3226923/20034704/93f74fb4-a402-11e6-92cd-87a4fcb6170d.png)

**Comment by suqi** [comment]
谢谢，由于以后主要使用gitbook线上版本持续更新，所以就不做PDF官方支持了，可以自行下载后生成。
