### ISSUE TITLE
SUMMARY.md文件中推荐阅读中Learn Python the Hard Way的链接已经失效

### ISSUE THREAD

**Issue by OuterCloud** [eastlakeside/interpy-zh#55]
在SUMMARY.dm文件中，目录最后的推荐阅读（https://github.com/eastlakeside/interpy-zh/blob/master/SUMMARY.md ）中， Learn Python the Hard Way的那个链接已经失效啦，详见：
https://github.com/eastlakeside/interpy-zh/blob/master/seealso.md

**Comment by OuterCloud** [comment]
Learn Python the Hard Way

**Comment by liuyu** [comment]
已修复。谢谢反馈
