### ISSUE TITLE
排版错误

### ISSUE THREAD

**Issue by DefuLi** [eastlakeside/interpy-zh#61]
在pdf35页，最后一句话出现了两个错误。
1、多了一个括号
2、应该是"now you are in the welcome() function" 而不是 "now you are in the greet() function"

![image](https://user-images.githubusercontent.com/33721251/69059512-a596b400-0a50-11ea-867e-77b5ae585799.png)

**Comment by muxueqz** [comment]
这个不是错误
1. 括号是正确的，这是从函数返回函数
2. 你可以自己执行一下，结果是`now you are in the greet() function`

```bash
$ cat test.py
def hi(name="yasoob"):
    def greet():
        return "now you are in the greet() function"

    def welcome():
        return "now you are in the welcome() function"

    if name == "yasoob":
        return greet
    else:
        return welcome

a = hi()
print(a)
print(hi()())
$ python test.py
<function greet at 0x7f25d80cb150>
now you are in the greet() function
```
