### ISSUE TITLE
带参数的装饰器的最后一个示例email_logit写的有问题，运行报错

### ISSUE THREAD

**Issue by wd7755** [eastlakeside/interpy-zh#71]
运行代码：
```
email_logit._logfile = 'out3.log' # 如果需要修改log文件参数
@email_logit
def myfunc2():
    pass

myfunc2()
```
错误如下：
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> /tmp/ipykernel_74/2250255109.py in <module>
>       1 email_logit._logfile = 'out3.log' # 如果需要修改log文件参数
>       2 @email_logit
> ----> 3 def myfunc2():
>       4     pass
>       5 
> 
> /tmp/ipykernel_74/2465603354.py in __init__(self, email, *args, **kwargs)
>       5     def __init__(self,  email='admin@myproject.com',*args, **kwargs):
>       6         self.email = email
> ----> 7         super(email_logit, self).__init__(*args, **kwargs)
>       8 
>       9     def notify(self):
> 
> TypeError: __init__() missing 1 required positional argument: 'func'

我进行了修改，修改后的email_logit代码如下：
```
class email_logit(logit):
    '''
    一个logit的实现版本，可以在函数调用时发送email给管理员
    '''
    def __init__(self, func, email='admin@myproject.com',*args, **kwargs):
        self.email = email
        super(email_logit, self).__init__(func,*args, **kwargs)

    def notify(self):
        # 发送一封email到self.email
        # 这里就不做实现了
        print("Send email!")
        pass
```
再次运行后结果如下：

> myfunc2 was called
> Send email!

**Comment by suqi** [comment]
非常感谢 @wd7755 的指正，已修复
