### ISSUE TITLE
页面显示 404 https://py.eastlakeside.cn/book/Extras/targeting_python2+3.html

### ISSUE THREAD

**Issue by hao1032** [eastlakeside/interpy-zh#73]
https://py.eastlakeside.cn/book/Extras/targeting_python2+3.html
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/4860962/177457860-0f4ed3a6-3852-49f9-a843-5802a6d30d26.png">

**Comment by leida3669** [comment]
你的邮件已经收到。

**Comment by suqi** [comment]
Fixed, thanks a lot @leida3669 
https://github.com/eastlakeside/interpy-zh/pull/74/files
